services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - testnet

  consumer:
    build:
      context: ./consumer
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    networks:
      - testnet
    restart: unless-stopped

  producer:
    build:
      context: ./producer
      dockerfile: dockerfile
    ports:
      - '8888:8888'
    depends_on:
      - consumer
      - kafka
    links:
      - consumer
      - kafka
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet:
    driver: bridge